name: lebonmeeple

services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend-network

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: backend-prod
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SECRET_KEY=SECRET_KEY
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - backend-network

  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: frontend-prod
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - backend
    ports:
      - '3001:3000'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  db-data:

networks:
  backend-network:
    driver: bridge
