name: le-bon-meeple

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: backend-prod
    container_name: backend
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true

  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: frontend-prod
    container_name: frontend
    ports:
      - '127.0.0.1:3001:3000'
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - '127.0.0.1:8080:8080'

volumes:
  pgdata:
