name: le-bon-meeple

services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: backend
    container_name: backend
    command: ["sh", "-c", "npm install && npm run prisma:generate && sh ./apps/back-end/start.sh"]
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    volumes:
      - .:/app
    user: root

  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: frontend
    container_name: frontend
    command: ["sh", "-c", "npm install && npm run front:dev"]
    ports:
      - '127.0.0.1:3001:3000'
    volumes:
      - .:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    depends_on:
      - backend
    user: root


  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    ports:
      - '127.0.0.1:8080:8080'

volumes:
  pgdata:
