FROM node:20-alpine AS base
WORKDIR /app
RUN chown -R node:node /app
USER node

FROM base AS base-dev
COPY --chown=node:node ./package*.json ./
RUN npm ci

FROM base-dev AS backend-dev
COPY --chown=node:node . .
WORKDIR /app/apps/back-end
ENV NODE_ENV=development
CMD ["sh", "-c", "npm run api:start:dev"]

FROM base-dev AS frontend-dev
COPY --chown=node:node . .
WORKDIR /app/apps/front-end
ENV NODE_ENV=development
CMD ["npm", "run", "front:dev"]
