name: le-bon-meeple

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.backend
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    command: 'bash -c "npm run prisma:migrate && npm run api:start:dev"'

  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    depends_on:
      - backend
    command: 'npm run front:dev'

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  pgdata:
