name: le-bon-meeple

services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

  backend:
    image: 590184137944.dkr.ecr.eu-west-3.amazonaws.com/lebonmeeple-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: backend-prod
    container_name: backend
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SECRET_KEY=SECRET_KEY

  frontend:
    image: 590184137944.dkr.ecr.eu-west-3.amazonaws.com/lebonmeeple-frontend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: frontend-prod
    container_name: frontend
    ports:
      - '127.0.0.1:3001:3000'
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - '127.0.0.1:8080:8080'

volumes:
  pgdata:
