export const gamesSeedData = [
  {
    name: 'Gloomhaven',
    year: '2017',
    rating: 8.9,
    mechanics: [
      'Action Points',
      'Campaign',
      'Cooperative Play',
      'Deck Construction',
      'Variable Player Powers',
    ],
    image: '/games/gloomhaven.webp',
    minPlayers: 1,
    maxPlayers: 4,
    duration: 120,
    difficulty: 'High',
  },
  {
    name: 'Pandemic',
    year: '2008',
    rating: 8.2,
    mechanics: ['Cooperative Play', 'Set Collection', 'Variable Player Powers'],
    image: '/games/pandemic_legacy.webp',
    minPlayers: 2,
    maxPlayers: 4,
    duration: 45,
    difficulty: 'Medium',
  },
  {
    name: 'Azul',
    year: '2017',
    rating: 7.9,
    mechanics: ['Pattern Building', 'Tile Placement'],
    image: '/games/azul.webp',
    minPlayers: 2,
    maxPlayers: 4,
    duration: 30,
    difficulty: 'Low',
  },
  {
    name: 'Codenames',
    year: '2015',
    rating: 7.8,
    mechanics: ['Word Game', 'Team-Based Game'],
    image: '/games/codenames.webp',
    minPlayers: 4,
    maxPlayers: 8,
    duration: 30,
    difficulty: 'Low',
  },
  {
    name: 'Terraforming Mars',
    year: '2016',
    rating: 8.3,
    mechanics: [
      'Action Points',
      'Engine Building',
      'Hand Management',
      'Set Collection',
    ],
    image: '/games/terraforming_mars.webp',
    minPlayers: 1,
    maxPlayers: 5,
    duration: 120,
    difficulty: 'Medium',
  },
  {
    name: 'Wingspan',
    year: '2019',
    rating: 8.1,
    mechanics: ['Engine Building', 'Set Collection', 'Card Drafting'],
    image: '/games/wingspan.webp',
    minPlayers: 1,
    maxPlayers: 5,
    duration: 40,
    difficulty: 'Medium',
  },
  {
    name: 'Carcassonne',
    year: '2000',
    rating: 7.4,
    mechanics: ['Tile Placement', 'Area Control / Area Influence'],
    image: '/games/carcassonne.webp',
    minPlayers: 2,
    maxPlayers: 5,
    duration: 35,
    difficulty: 'Low',
  },
  {
    name: '7 Wonders',
    year: '2010',
    rating: 7.8,
    mechanics: [
      'Card Drafting',
      'Set Collection',
      'Simultaneous Action Selection',
    ],
    image: '/games/7_wonders.webp',
    minPlayers: 3,
    maxPlayers: 7,
    duration: 30,
    difficulty: 'Medium',
  },
  {
    name: 'Ticket to Ride',
    year: '2004',
    rating: 7.5,
    mechanics: ['Set Collection', 'Route Building'],
    image: '/games/ticket_to_ride.webp',
    minPlayers: 2,
    maxPlayers: 5,
    duration: 60,
    difficulty: 'Low',
  },
  {
    name: 'Splendor',
    year: '2014',
    rating: 7.5,
    mechanics: ['Set Collection', 'Push Your Luck', 'Card Drafting'],
    image: '/games/splendor.webp',
    minPlayers: 2,
    maxPlayers: 4,
    duration: 30,
    difficulty: 'Low',
  },
  {
    name: 'Root',
    year: '2018',
    rating: 8.1,
    mechanics: [
      'Area Control / Area Influence',
      'Variable Player Powers',
      'Hand Management',
    ],
    image: '/games/root.webp',
    minPlayers: 2,
    maxPlayers: 4,
    duration: 60,
    difficulty: 'Medium',
  },
  {
    name: 'Scythe',
    year: '2016',
    rating: 8.2,
    mechanics: [
      'Area Control / Area Influence',
      'Engine Building',
      'Combat',
      'Resource Management',
    ],
    image: '/games/scythe.webp',
    minPlayers: 2,
    maxPlayers: 7,
    duration: 90,
    difficulty: 'Medium',
  },
];
