export const gamesSeedData = [
  {
    name: 'Gloomhaven',
    year: '2017',
    rating: 8.9,
    mechanics: [
      'Action Points',
      'Campaign',
      'Cooperative Play',
      'Deck Construction',
      'Variable Player Powers',
    ],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 1,
    maxPlayers: 4,
    duration: 120,
    difficulty: 'High',
  },
  {
    name: 'Pandemic',
    year: '2008',
    rating: 8.2,
    mechanics: ['Cooperative Play', 'Set Collection', 'Variable Player Powers'],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 4,
    duration: 45,
    difficulty: 'Medium',
  },
  {
    name: 'Azul',
    year: '2017',
    rating: 7.9,
    mechanics: ['Pattern Building', 'Tile Placement'],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 4,
    duration: 30,
    difficulty: 'Low',
  },
  {
    name: 'Codenames',
    year: '2015',
    rating: 7.8,
    mechanics: ['Word Game', 'Team-Based Game'],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 4,
    maxPlayers: 8,
    duration: 30,
    difficulty: 'Low',
  },
  {
    name: 'Terraforming Mars',
    year: '2016',
    rating: 8.3,
    mechanics: [
      'Action Points',
      'Engine Building',
      'Hand Management',
      'Set Collection',
    ],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 1,
    maxPlayers: 5,
    duration: 120,
    difficulty: 'Medium',
  },
  {
    name: 'Wingspan',
    year: '2019',
    rating: 8.1,
    mechanics: ['Engine Building', 'Set Collection', 'Card Drafting'],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 1,
    maxPlayers: 5,
    duration: 40,
    difficulty: 'Medium',
  },
  {
    name: 'Carcassonne',
    year: '2000',
    rating: 7.4,
    mechanics: ['Tile Placement', 'Area Control / Area Influence'],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 5,
    duration: 35,
    difficulty: 'Low',
  },
  {
    name: 'Dominion',
    year: '2008',
    rating: 7.6,
    mechanics: ['Deck Building', 'Set Collection'],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 4,
    duration: 30,
    difficulty: 'Medium',
  },
  {
    name: '7 Wonders',
    year: '2010',
    rating: 7.8,
    mechanics: [
      'Card Drafting',
      'Set Collection',
      'Simultaneous Action Selection',
    ],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 3,
    maxPlayers: 7,
    duration: 30,
    difficulty: 'Medium',
  },
  {
    name: 'Ticket to Ride',
    year: '2004',
    rating: 7.5,
    mechanics: ['Set Collection', 'Route Building'],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 5,
    duration: 60,
    difficulty: 'Low',
  },
  {
    name: 'Splendor',
    year: '2014',
    rating: 7.5,
    mechanics: ['Set Collection', 'Push Your Luck', 'Card Drafting'],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 4,
    duration: 30,
    difficulty: 'Low',
  },
  {
    name: 'King of Tokyo',
    year: '2011',
    rating: 7.3,
    mechanics: [
      'Dice Rolling',
      'Area Control / Area Influence',
      'Set Collection',
    ],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 6,
    duration: 30,
    difficulty: 'Low',
  },
  {
    name: 'Agricola',
    year: '2007',
    rating: 7.9,
    mechanics: ['Action Points', 'Worker Placement', 'Set Collection'],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 1,
    maxPlayers: 5,
    duration: 120,
    difficulty: 'High',
  },
  {
    name: 'Caverna: The Cave Farmers',
    year: '2013',
    rating: 7.8,
    mechanics: [
      'Action Points',
      'Worker Placement',
      'Tile Placement',
      'Set Collection',
    ],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 1,
    maxPlayers: 7,
    duration: 120,
    difficulty: 'High',
  },
  {
    name: 'Root',
    year: '2018',
    rating: 8.1,
    mechanics: [
      'Area Control / Area Influence',
      'Variable Player Powers',
      'Hand Management',
    ],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 4,
    duration: 60,
    difficulty: 'Medium',
  },
  {
    name: 'Scythe',
    year: '2016',
    rating: 8.2,
    mechanics: [
      'Area Control / Area Influence',
      'Engine Building',
      'Combat',
      'Resource Management',
    ],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 7,
    duration: 90,
    difficulty: 'Medium',
  },
  {
    name: 'Twilight Struggle',
    year: '2005',
    rating: 8.4,
    mechanics: [
      'Card Driven',
      'Area Control / Area Influence',
      'Simultaneous Action Selection',
    ],
    image:
      'https://cf.geekdo-images.com/original/img/0i9yZfV7gkQ9Q3cW5r0Vjzq2K9s=/0x0/pic3582969.jpg',
    minPlayers: 2,
    maxPlayers: 2,
    duration: 180,
    difficulty: 'High',
  },
];
