FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY apps/back-end ./apps/back-end
EXPOSE 3000
# Copie le script de démarrage
COPY apps/back-end/start.sh ./apps/back-end/start.sh
RUN chmod +x ./apps/back-end/start.sh
CMD ["sh", "./apps/back-end/start.sh"]