name: Run tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
        env:
          PGPASSWORD: postgres

      - name: Run migrations
        run: npm run prisma:migrate
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - name: Run tests
        run: npm run api:test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
